name: CIpull_request_target

on:
  pull_request_target:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: get actor
        run: echo "${{ github.actor }}"

      - name: Run a one-line script
        run: bash main.sh
        env:
          secret_myql_pass: ${{secrets.LALALA}}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "good bye from main pull_request_target!"
